name: Trigger Azure DevOps Pipeline on PR Ready for Review

on:
  pull_request:
    types: [ready_for_review]

jobs:
  trigger-azure-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Trigger Azure DevOps Pipeline
        env:
          AZURE_DEVOPS_ORG: ACSEP
          AZURE_DEVOPS_PROJECT: OW
          AZURE_DEVOPS_PIPELINE_ID: 2
          AZURE_DEVOPS_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }}
        run: |
          pr_branch=$(jq -r .pull_request.head.ref < $GITHUB_EVENT_PATH)
          echo "Pull request branch: $pr_branch"

          echo "Triggering Azure DevOps Pipeline..."
          response=$(curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Basic $(echo -n :$AZURE_DEVOPS_TOKEN | base64)" \
            -d '{
                  "definition": {
                    "id": '"$AZURE_DEVOPS_PIPELINE_ID"'
                  },
                  "sourceBranch": "refs/heads/'"$pr_branch"'"
                }' \
            "https://dev.azure.com/$AZURE_DEVOPS_ORG/$AZURE_DEVOPS_PROJECT/_apis/build/builds?api-version=6.0")

          echo "Response from Azure DevOps API:"
          echo "$response"

          status_code=$(echo "$response" | jq -r .status)
          if [[ "$status_code" != "201" ]]; then
            echo "Failed to trigger Azure DevOps Pipeline. Status code: $status_code"
            exit 1
          fi

          echo "Successfully triggered Azure DevOps Pipeline."
