name: Trigger Azure DevOps Pipeline on PR Approval

on:
  pull_request_review:
    types: [submitted]

jobs:
  trigger-azure-pipeline:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - name: Trigger Azure DevOps Pipeline
        env:
          AZURE_DEVOPS_ORG: ACSEP
          AZURE_DEVOPS_PROJECT: OW
          AZURE_DEVOPS_PIPELINE_ID: 2
          AZURE_DEVOPS_TOKEN: ntc33huyg3uaexwsj4wppomgkefqxu6kzuu5h3jpmwabtot6cxiq
        run: |
          pr_branch=$(jq -r .pull_request.head.ref < $GITHUB_EVENT_PATH)
          echo "Pull request branch: $pr_branch"
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Basic $(echo -n :$AZURE_DEVOPS_TOKEN | base64)" \
            -d '{
                  "definition": {
                    "id": '"$AZURE_DEVOPS_PIPELINE_ID"'
                  },
                  "sourceBranch": "refs/heads/'"$pr_branch"'"
                }' \
            "https://dev.azure.com/$AZURE_DEVOPS_ORG/$AZURE_DEVOPS_PROJECT/_apis/build/builds?api-version=6.0"
